---
title: Substrate roughness affects stream benthic algal diversity, assemblage composition, and nestedness 

authors: ["admin", "A. Schwarzbold", "A.S. Melo"]



date: "2011-09-01T00:00:00Z"
doi: "http://dx.doi.org/10.1899/11-044.1"


# Publication type.
# Legend: 0 = Uncategorized; 1 = Conference paper; 2 = Journal article;
# 3 = Preprint / Working Paper; 4 = Report; 5 = Book; 6 = Book section;
# 7 = Thesis; 8 = Patent
publication_types: ["2"]

# Publication name and optional abbreviated publication name.
publication: "*Journal of the North American Benthological Society*"
publication_short: ""

abstract: "Heterogeneity generated by irregularities on the surface of streambed substrates is an important determinant of local species diversity of algae. However, few investigators have examined the effects of substrate roughness on the composition of algal growth forms and on patterns of species distribution. We examined the influence of substrate roughness on stream benthic algal assemblages through a field experiment with 2 treatments (smooth and rough artificial substrates for algal colonization). We assessed whether species richness, density, and assemblage composition of benthic algae (all taxa and those in 5 growth-form groups) differed between treatments and whether differences in species composition between substrates were the result of species turnover or nestedness. We also used a data subsampling procedure to investigate the effect of differences in species richness between treatments. Total species richness was higher on rough than on smooth substrates, but density did not differ between treatments. Species richness, density, and composition of the adnate/prostrate growth form did not differ between treatments. The erect/stalked growth form had higher species richness on rough substrates, but did not differ in density between treatments. All other growth forms (filamentous, motile, and metaphyton) had higher species richness and density on rough substrates and differed in species composition between substrates. The results of the subsampling analysis indicated that assemblage composition was affected by differences in species richness and by changes in species composition (i.e., turnover). Species distribution had a nested pattern, in which the assemblages on smooth substrates were a subgroup of the species occurring on rough substrates. We suggest that the differences in assemblage composition between smooth and rough substrates resulted from variability in species’ capabilities to colonize substrates with or without crevices. This variability resulted in both nestedness and turnover."
#tags:
#- Source Themes
#featured: false

#links:
#- name: ""
#   url: ""
url_pdf: ""
url_code: ''
url_dataset: ''
url_poster: ''
url_project: ''
url_slides: ''
url_source: ''
url_video: ''

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder. 
image:
  caption: ''
  focal_point: ""
  preview_only: false

# Associated Projects (optional).
#   Associate this publication with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `internal-project` references `content/project/internal-project/index.md`.
#   Otherwise, set `projects: []`.
projects: []

# Slides (optional).
#   Associate this publication with Markdown slides.
#   Simply enter your slide deck's filename without extension.
#   E.g. `slides: "example"` references `content/slides/example/index.md`.
#   Otherwise, set `slides: ""`.
slides: ""
---
